### ISSUE TITLE
Images not showing in 11.0.4

### ISSUE THREAD

**Issue by MorneL** [ispyropoulos/intl-tel-input-rails#18]
We have updated our gem to 11.0.4 from 9.0.0 and now the flag icon isn't showing unless I add the line 

> .iti-flag {background-image: image-url("flags.png");}

**Comment by bigzoo** [comment]
Same thing here @MorneL

**Comment by ispyropoulos** [comment]
This unfortunately broke since last release. The gem now contains the default image path, which needs to be overridden (as also explained [here](https://github.com/jackocnr/intl-tel-input#getting-started)). In our case, this needs to point to the asset pipeline root.

I will fix this and release an update. Feel free to contribute the fix yourself if you wish 😉

**Comment by ispyropoulos** [comment]
This is now fixed in 9baac738c5e57905f36aba4483416067dd240ec6. Thanks @metalkoholic!
